/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './busy.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from './busy.service';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from './busy.component.ngfactory';
import * as import7 from './busy-backdrop.component.ngfactory';
import * as import8 from '@angular/core/src/i18n/tokens';
import * as import9 from './busy-config';
class BusyModuleInjector extends import0.NgModuleInjector<import1.BusyModule> {
  _CommonModule_0:import2.CommonModule;
  _BusyModule_1:import1.BusyModule;
  __NgLocalization_2:import3.NgLocaleLocalization;
  __BusyService_3:import4.BusyService;
  constructor(parent:import5.Injector) {
    super(parent,[
      import6.BusyComponentNgFactory,
      import7.BusyBackdropComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_2():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import3.NgLocaleLocalization(this.parent.get(import8.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _BusyService_3():import4.BusyService {
    if ((this.__BusyService_3 == null)) { (this.__BusyService_3 = new import4.BusyService(this.parent.get(import9.BusyConfig,(null as any)))); }
    return this.__BusyService_3;
  }
  createInternal():import1.BusyModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._BusyModule_1 = new import1.BusyModule();
    return this._BusyModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.BusyModule)) { return this._BusyModule_1; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import4.BusyService)) { return this._BusyService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BusyModuleNgFactory:import0.NgModuleFactory<import1.BusyModule> = new import0.NgModuleFactory(BusyModuleInjector,import1.BusyModule);